from datetime import datetime
import os

from model_pipeline import predict_heart_risk
from explainable_ai import explain_prediction
from health_recommendations import generate_health_recommendations


def generate_patient_report(patient_name, input_data, output_path="reports"):

    os.makedirs(output_path, exist_ok=True)

    # -------- ML Prediction --------
    probability, risk_level = predict_heart_risk(input_data)

    # -------- Explainability --------
    explanation = explain_prediction(input_data)

    # 🔥 FIX ADDED HERE
    explanation = [
        {"feature": k, "impact": v}
        for k, v in explanation.items()
    ]

    # -------- Health Recommendations --------
    recommendations = generate_health_recommendations(input_data)

    # -------- Timestamp --------
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    safe_name = patient_name.replace(" ", "_")
    filename = f"{safe_name}_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.html"
    file_path = os.path.join(output_path, filename)

    html_content = f"""
    <html>
    <head>
        <title>Heart Disease Risk Report</title>
        <style>
            body {{ font-family: Arial, sans-serif; margin: 40px; }}
            h1 {{ color: #b30000; }}
            h2 {{ color: #333; }}
            .low {{ color: green; }}
            .moderate {{ color: orange; }}
            .high {{ color: red; }}
            ul {{ line-height: 1.6; }}
            .box {{ padding: 15px; border: 1px solid #ccc; margin-bottom: 20px; }}
        </style>
    </head>

    <body>
        <h1>Heart Disease Risk Assessment Report</h1>

        <p><strong>Patient Name:</strong> {patient_name}</p>
        <p><strong>Date:</strong> {timestamp}</p>

        <div class="box">
            <h2>Risk Summary</h2>
            <p><strong>Risk Probability:</strong> {probability}%</p>
            <p><strong>Risk Category:</strong>
                <span class="{risk_level.lower()}">{risk_level} Risk</span>
            </p>
        </div>

        <div class="box">
            <h2>Patient Input Details</h2>
            <ul>
                {''.join(f"<li><strong>{k.replace('_',' ').title()}:</strong> {v}</li>" for k, v in input_data.items())}
            </ul>
        </div>

        <div class="box">
            <h2>Major Risk Factors</h2>
            <ul>
                {''.join(f"<li>{item['feature'].replace('_',' ').title()}</li>" for item in explanation if item['impact'] > 0)}
            </ul>
        </div>

        <div class="box">
            <h2>Personalized Health Recommendations</h2>
            <ul>
                {''.join(f"<li>{rec}</li>" for rec in recommendations)}
            </ul>
        </div>

        <div class="box">
            <h2>Disclaimer</h2>
            <p>
                This report is generated by a machine learning model for educational purposes only.
                It does not replace professional medical advice or diagnosis.
            </p>
        </div>
    </body>
    </html>
    """

    with open(file_path, "w", encoding="utf-8") as f:
        f.write(html_content)

    return file_path